spring.application.name=backend
spring.data.mongodb.uri=${MONGODB_URI}
#spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.database=${MONGODB_DATABASE:stayease}
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# Brevo Mail
brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}

# Twilio SMS Setup
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}